export  const data = [
  {
    id: 1,
    attributes: {
      URLText: "Event",
      corporate:"ABOUT EVENT",
      description:"Our event brings together industry leaders, innovators, and passionate individuals for an unforgettable experience. From inspiring keynote speeches to hands-on workshops, this event offers opportunities for networking, learning, and growth. Join us for a day filled with insightful discussions, engaging activities, and valuable connections. Whether you're looking to expand your knowledge or connect with like-minded individuals, this event is designed to meet your needs. Don’t miss out on this exciting opportunity to be a part of something big!",
      title1:"Event Overview",
      bulletpoints1: "Event Highlights",
      bulletpoints2: "Special Guests",
      bulletpoints3: "Venue Information",
      bulletpoints4: "Event Schedule",
      bulletpoints5: "Ticketing Information",
      bulletpoints6: "Registration Details",
      bulletpoints7: "Event Sponsors",
      bulletpoints8: "Past Event Success",
      bulletpoints9: "Upcoming Events",
      bulletpoints10: "Event Partners",
      bulletpoints11: "Event Collaborations",
      bulletpoints12: "Event Media",
      contact:"Contact Us",
      contactdescription:"Reach out for event inquiries and more.",
      onHover:true,
      url: "/events",
      createdAt: "2024-06-04T09:37:28.020Z",
      updatedAt: "2024-06-04T09:37:29.014Z",
      publishedAt: "2024-06-04T09:37:29.011Z",
     
      urlicon: {
        data: null,
      },
    },
  },
  {
    id: 2,
    attributes: {
      URLText: "Corporate",
      corporate:"ABOUT CORPORATE",
      description: "The 'Corporate' section gives you a glimpse into our thriving business culture and operations. Discover how we drive innovation, foster growth, and build long-lasting partnerships. Learn about our corporate philosophy, the talented team behind our success, and our commitment to social responsibility. Dive into our core values, vision, and explore the industries we influence. This section also provides a deeper look into our corporate events, achievements, and strategies for global expansion.",
      title1:"Corporate Overview",
      bulletpoints1: "Corporate Vision",
      bulletpoints2: "Mission & Values",
      bulletpoints3: "Leadership Team",
      bulletpoints4: "Corporate Strategy",
      bulletpoints5: "Sustainability Initiatives",
      bulletpoints6: "Business Achievements",
      bulletpoints7: "Innovation at Work",
      bulletpoints8: "Global Presence",
      bulletpoints9: "Corporate Social Responsibility",
      bulletpoints10: "Industry Recognition",
      bulletpoints11: "Key Partnerships",
      bulletpoints12: "Our Clients",
      contact:"Contact Corporate",
      contactdescription:"For corporate inquiries, reach out here.",
      onHover:true,
      url: "/corporate",
      createdAt: "2024-06-04T09:40:16.115Z",
      updatedAt: "2024-06-04T09:40:17.431Z",
      publishedAt: "2024-06-04T09:40:17.428Z",
      urlicon: {
        data: null,
      },
    },
  },
  {
    id: 3,
    attributes: {
      URLText: "Wedding",
      corporate:"ABOUT WEDDING",
      description:"Explore the beauty and elegance of weddings through our comprehensive wedding section. From the latest trends in bridal fashion to destination wedding venues, we cover all aspects of creating a dream wedding experience. Whether you're planning your own wedding or just seeking inspiration, find everything you need from wedding planning tips, vendor recommendations, budgeting advice, and personalized services. Get insights into wedding photography, guest experiences, and unique ways to make your celebration unforgettable.",
      title1:"Wedding Overview",
      bulletpoints1: "Wedding Themes & Trends",
      bulletpoints2: "Venue Selection",
      bulletpoints3: "Bridal Party Roles",
      bulletpoints4: "Wedding Planning Checklist",
      bulletpoints5: "Vendors & Partners",
      bulletpoints6: "Wedding Timeline",
      bulletpoints7: "RSVP Details",
      bulletpoints8: "Bridal Gowns",
      bulletpoints9: "Photography & Videography",
      bulletpoints10: "Honeymoon Packages",
      bulletpoints11: "Wedding Budgeting",
      bulletpoints12: "Guest Experience",
      contact:"Contact Wedding",
      contactdescription:"Reach out for wedding inquiries and assistance.",
      url: "/wedding",
      onHover:true,
      createdAt: "2024-06-04T09:40:16.115Z",
      updatedAt: "2024-06-04T09:40:17.431Z",
      publishedAt: "2024-06-04T09:40:17.428Z",
      urlicon: {
        data: null,
      },
    },
  },
    {
      id: 4,
      attributes: {
        URLText: "M&M",
        url: "/m&m",
        createdAt: "2024-06-04T09:40:16.115Z",
        updatedAt: "2024-06-04T09:40:17.431Z",
        publishedAt: "2024-06-04T09:40:17.428Z",
        onHover:false,
        urlicon: {
          data: null,
        },
      },
    },
    {
      id: 5,
      attributes: {
        URLText: "Journal",
        corporate:"About JOURNAL",
        url: "#",
        createdAt: "2024-06-04T09:40:16.115Z",
        updatedAt: "2024-06-04T09:40:17.431Z",
        publishedAt: "2024-06-04T09:40:17.428Z",
        onHover:false,
        urlicon: {
          data: null,
        },
      },
    },
    {
      id: 6,
      attributes: {
        URLText: "Contact",
        corporate:"About CORPORATE",
        onHover:false,
        url: "/contact-us",
        createdAt: "2024-06-04T09:40:16.115Z",
        updatedAt: "2024-06-04T09:40:17.431Z",
        publishedAt: "2024-06-04T09:40:17.428Z",
    
        urlicon: {
          data: null,
        },
      },
    },
  ];